#!/bin/sh

xrandr | grep -q "DP2 connected"
ST=$?

if [ $ST -eq 0 ]; then
    xrandr --output eDP1 --mode 1920x1080 --output DP2 --auto --primary --left-of eDP1
else
    xrandr --output eDP1 --mode 1920x1080 --primary
fi

# Send first 4 workspaces to primary output
i3-msg '[workspace="^(1|2|3|4)"] exec send_to_primary;'
